"""initial_schema_api_aponta

Revision ID: 90324eefb107
Revises: 
Create Date: 2026-01-09 08:44:53.475736

"""
from typing import Sequence, Union  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
import os

# Adicionar o diretório raiz ao path para importar app.config
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

# revision identifiers, used by Alembic.
revision: str = '90324eefb107'
down_revision: Union[str, None] = 'ebd442876620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Get schema dynamically from environment, not from cached settings
def get_db_schema():
    """Get database schema from environment variable"""
    # Try to get from environment first, fallback to config
    import os
    schema = os.getenv('DATABASE_SCHEMA')
    if schema:
        return schema
    # If not in environment, use config (for backward compatibility)
    from app.config import Settings
    return Settings().database_schema


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    db_schema = get_db_schema()
    
    # Criar schema se não existir
    try:
        bind.execute(sa.text(f"CREATE SCHEMA IF NOT EXISTS {db_schema}"))
        bind.commit()
    except Exception:
        pass  # Schema pode já existir
    
    # Verificar tabelas existentes no schema correto
    existing_tables = inspector.get_table_names(schema=db_schema)

    if 'atividades' not in existing_tables:
        op.create_table('atividades',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('id_projeto', sa.UUID(), nullable=False, comment='Project ID from Azure Boards (Azure DevOps)'),
        sa.Column('criado_em', sa.DateTime(), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema=db_schema
        )
        op.create_index(op.f('ix_api_aponta_atividades_id'), 'atividades', ['id'], unique=False, schema=db_schema)
        op.create_index(op.f('ix_api_aponta_atividades_id_projeto'), 'atividades', ['id_projeto'], unique=False, schema=db_schema)
        op.create_index(op.f('ix_api_aponta_atividades_nome'), 'atividades', ['nome'], unique=False, schema=db_schema)
    
    if 'projetos' not in existing_tables:
        op.create_table('projetos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('external_id', sa.UUID(), nullable=False, comment='ID do projeto no Azure DevOps'),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('estado', sa.String(), nullable=True, comment='Estado do projeto (wellFormed, deleting, etc)'),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Data da última sincronização'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema=db_schema
        )
        op.create_index(op.f('ix_api_aponta_projetos_external_id'), 'projetos', ['external_id'], unique=True, schema=db_schema)
        op.create_index(op.f('ix_api_aponta_projetos_nome'), 'projetos', ['nome'], unique=False, schema=db_schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    db_schema = get_db_schema()
    op.drop_index(op.f('ix_api_aponta_projetos_nome'), table_name='projetos', schema=db_schema)
    op.drop_index(op.f('ix_api_aponta_projetos_external_id'), table_name='projetos', schema=db_schema)
    op.drop_table('projetos', schema=db_schema)
    op.drop_index(op.f('ix_api_aponta_atividades_nome'), table_name='atividades', schema=db_schema)
    op.drop_index(op.f('ix_api_aponta_atividades_id_projeto'), table_name='atividades', schema=db_schema)
    op.drop_index(op.f('ix_api_aponta_atividades_id'), table_name='atividades', schema=db_schema)
    op.drop_table('atividades', schema=db_schema)
    # ### end Alembic commands ###
